# more on http://wiki.ros.org/navigation/Tutorials/RobotSetup

local_costmap:
  update_frequency: 10.0
  publish_frequency: 2.0
  transform_tolerance: 0.5 # [s]
  footprint: [[0.4, 0.4], [0.4, -0.4], [-0.4, -0.4], [-0.4, 0.4]]  # footprint fo the robot, centered in robot centre
  # robot_radius: 0.4 # Just use radius now instead of footprint (To speedup collision checking)

  rolling_window: true
  width: 8.0
  height: 8.0
  resolution: 0.05
  
  plugins:
    - 
     name: obstacle_layer
     type: "costmap_2d::ObstacleLayer"  
    -
     name: inflation_layer
     type: "costmap_2d::InflationLayer"

  virtual_obstacles:
    observation_sources: laser_scan_sensor
    
  obstacle_layer:
    enabled: true
    observation_sources: laser_scan_sensor 
    laser_scan_sensor:
      data_type: 'LaserScan'
      topic: scan
      marking: true
      clearing: true
      min_obstacle_height: -100.0
      max_obstacle_height: 100.0
      observation_persistence: 0.4
      inf_is_valid: true   

  inflation_layer:
    enabled: true
    observation_sources: laser_scan_sensor
    inflation_radius: 0.4
    cost_scaling_factor: 1.0