# more on http://wiki.ros.org/move_base

controller_frequency: 0.1
recovery_behavior_enabled: true
clearing_rotation_allowed: false

NavfnROS:
  allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.2 # A tolerance on the goal point for the planner.

TebLocalPlannerROS:
  # Trajectory
  teb_autosize: True
  dt_ref: 0.3
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: true
  max_global_plan_lookahead_dist: 3.0
  feasibility_check_no_poses: 5
  allow_init_with_backwards_motion: true
  global_plan_viapoint_sep: 0.5

  # Robot
  max_vel_x: 1.0
  max_vel_y: 0.0
  max_vel_x_backwards: 1.0
  max_vel_y_backwards: 1.0
  max_vel_theta: 1.0
  acc_lim_x: 4.0
  acc_lim_y: 0.0
  acc_lim_theta: 2.0
  wheelbase: 0.625
  min_turning_radius: 1.0
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "circular"
    radius: 0.75 # for type "circular"
    line_start: [-0.3, 0.0] # for type "line"
    line_end: [0.3, 0.0] # for type "line"
    front_offset: 0.2 # for type "two_circles"
    front_radius: 0.2 # for type "two_circles"
    rear_offset: 0.2 # for type "two_circles"
    rear_radius: 0.2 # for type "two_circles"
    vertices: [ [0.4, 0.4], [0.4, -0.4], [-0.4, -0.4], [-0.4, 0.4] ] # for type "polygon"

  # GoalTolerance
  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 0.3
  free_goal_vel: false
  complete_global_plan: false

  # Obstacles
  min_obstacle_dist: 0.3
  inflation_dist: 0.4
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 3.0
  obstacle_poses_affected: 50
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5

  # Optimization
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.1
  weight_max_vel_x: 2
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 1.0
  weight_kinematics_turning_radius: 0.5
  weight_optimaltime: 25.0
  weight_shortest_path: 1.0
  weight_obstacle: 1
  weight_viapoint: 5.0 # Increase to stick closer to global plan
  weight_dynamic_obstacle: 10 # not in use yet
  selection_alternative_time_cost: False # not in use yet

  # Homotopy Class Planner
  enable_homotopy_class_planning: False
  enable_multithreading: True
  simple_exploration: True
  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 0.5
  free_goal_vel: false
  max_number_classes: 4
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: False
  delete_detours_backwards: True
  max_ratio_detours_duration_best_duration: 3.0

